extends Node

# UI signals
signal update_selected_world
signal update_save_btn_disabled

# Profile Signals
signal save_active_profile
signal update_active_profile_name
signal active_profile_changed
signal load_active_profile
signal profile_loaded
signal active_profile_equals_orig_profile
signal read_active_profile
signal broadcast_active_profile
signal load_profile
